Update Category.php
Fix for

Exception: Deprecated Functionality: Creation of dynamic property Magepow\MultiTranslate\Controller\Adminhtml\Catalog\Edit\Interceptor::$_resultRedirectFactory is deprecated